### ISSUE TITLE
How to install this

### ISSUE THREAD

**Issue by fastknight** [Athenodoros/TopHat#6]
There is no mention of how to start using this? I'm not familiar with SPAs on Github Pages - is there a basic howto available somewhere to provide a pointer of how to start using this?

Thanks.

**Comment by Athenodoros** [comment]
Hey @fastknight - it's a fair cop, there isn't much of an introduction and it's definitely not how people are used to using web apps... I'll have a look at adding some more explanation in.

For now, it's probably (hopefully!) more simple than you're expecting: it doesn't need to be installed, and you can just start using it directly in your browser. Any changes you make will be persisted when you re-open the page (let me know if that's not the case, and you're not in incognito mode or something!), and you can use the menus in the app to restart everything with either demo data or a clean slate. It won't share anything between computers or something, because everything is kept in your browser: you'll need to manage that yourself.

Does that answer the question? Happy to go into more detail if helpful.

**Comment by fastknight** [comment]
Thanks - that makes more sense now. I assumed that I needed to move this over to my own instance of github pages somehow but was completely lost on how to do this.

It would still be nice to be able to host the source locally, or even on my own Github Pages just so I know it doesn't disappear some day if I do start using it.

Finally, is there a way to share data across two different devices/browsers if it is all local? I can see the export tool so assume I would need to export and import across the two systems or is there a way to do a local sync somehow?

**Comment by Athenodoros** [comment]
You can definitely grab the code in case I do something bizarre - it's just a `git clone` away :D Although it's worth saying that everything about this is set up so that I have no incentive to do that: it's free for me to host, so even if I stopped using it I'd have no reason to take it down.

You're right about sync: there's no way to do automatic sync (it's hard to think how that would work without a backend to manage it), so you'd need to do it yourself. A big part of that could be the Dropbox sync, which will automatically push a copy of the export file whenever changes are made.
